server:
  port: 9195

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test?useSSL=false
    username: root
    password: purhar
    driver-class-name=com: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

  application:
    name: IDENTITY-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
