server:
  port: 9192

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test?useSSL=false
    username: root
    password: purhar
    driver-class-name=com: com.mysql.cj.jdbc.Driver
    initialization-mode: always


  application:
    name: PERSON-SERVICE

  config:
    import: configserver:http://localhost:9193



  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
