server:
  port: 9191

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test?useSSL=false
    username: root
    password: purhar
    driver-class-name=com: com.mysql.cj.jdbc.Driver
    initialization-mode: always


  application:
        name: ORDER-SERVICE

  config:
    import: configserver:http://localhost:9193



  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

